### ISSUE TITLE
Can you help me install it on Mac?

### ISSUE THREAD

**Issue by DeZ4p** [AtaMeydani/blum-bot#1]
I have two problems inside Mac:
1- pywin32. Not for Mac!
2- I have an error when installing this library
`pip install opencv-python --pre
Collecting opencv-python
  Using cached opencv-python-4.10.0.84.tar.gz (95.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]`
Is it possible to run this code for Mac?

**Comment by AtaMeydani** [comment]
> I have two problems inside Mac: 1- pywin32. Not for Mac! 2- I have an error when installing this library `pip install opencv-python --pre Collecting opencv-python Using cached opencv-python-4.10.0.84.tar.gz (95.1 MB) Installing build dependencies ... done Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [33 lines of output]` Is it possible to run this code for Mac?

Pywin32 is a Python extension that provides access to many Windows APIs, allowing developers to create Windows applications and interact with the Windows operating system using Python. However, pywin32 is specifically designed for Windows and is not compatible with macOS.

**Comment by AtaMeydani** [comment]
A new commit has been added
Refactor: Replace deprecated libraries with modern alternatives

- Replace pywin32 with pygetwindow for cross-platform window management
- Replace ctypes with pynput to handle keyboard input

This change improves cross-platform compatibility and uses more
actively maintained libraries. The new implementation should be
more robust and easier to maintain going forward.
